ALL_CATEGORIES = {
    "statistics": [
        "Unemployed",  # UTAH lol
        "Educated",  # Cali and Mass
        "Safe",
        "Dangerous",
        "Rich",  # Virginia??
        "Poor",  # LMAO Ohio
    ],
    "celebrities_of_interest": [
        "Kanye West from Graduation album",
        "Arnold Schwarzenegger",
        "Chief Keef",
        "Nick Saban",
        "Barack Obama",
    ],
    "questions": [
        "Best pizza",
        "Has the best BBQ",
        "Weather so good you'll regret where you live",
        "The greatest state in the united states",
        "Nice, but would slash your tires over college football",
        "Would win versus the world",
        "Lacks the capacity for critical thought",
    ],
    "vibes": [
        "Cowboy hats and country music",
        "Chill surfer vibe",
        "Alligators and swamps",
        "Gambling",
        "Corn as far as the eye can see",
        "Cold and angry",
        "Bass pro shop",
        "Clinically insane but chill",
        "The best looking people",
        "Peaked in the 90s",
        "American",
        "Scheming",
        "Sneak dissing",
        "Thinks they would survive a bear attack",
    ],
    "florida_headlines": [
        "Man Arrested for Throwing Alligator Through Wendy's Drive-Thru Window",
        "Man tries to rob gamestop while wearing a transparent bag on his head",
        "Man bites neighbor's ear off because he wouldn't give him a cigarette",
    ],
    "shrek_batch": [
        "Lord Farquad",
        "Puss in boots",
        "Shrek II",
        "Donkey from Shrek",
        "Shrek",
    ],
    "pop_culture": [
        "Shrek",
        "SpongeBob",
        "Barbie",
        "The Rock",
        "Taylor Swift",
        "Drake",
        "Beyoncé",
        "Elon Musk",
        "MrBeast",
        "Kim Kardashian",
        "Kanye West",
        "Harry Styles",
        "Billie Eilish",
        "Rihanna",
        "Tom Holland",
        "Zendaya",
        "Doja Cat",
        "Pedro Pascal",
        "Keanu Reeves",
        "Nicki Minaj",
    ],
    "fast_food_chains": [
        "McDonald's",
        "Taco Bell",
        "Chick-fil-A",
        "In-N-Out",
        "Wendy's",
        "Burger King",
        "Five Guys",
        "White Castle",
        "Jack in the Box",
        "Whataburger",
        "Popeyes",
        "Arby's",
        "KFC",
        "Sonic Drive-In",
        "Hardee's",
        "Carl's Jr.",
        "Culver's",
        "Shake Shack",
        "Raising Cane's",
        "Zaxby's",
    ],
    "conspiracies": [
        "Flat Earth",
        "Bigfoot",
        "Loch Ness Monster",
        "Moon Landing Hoax",
        "Chemtrails",
        "Denver Airport Conspiracy",
        "Reptilian Overlords",
        "Illuminati",
        "JFK Assassination",
        "Area 51",
        "Aliens",
        "HAARP",
        "QAnon",
        "Mandela Effect",
        "Paul is Dead",
        "5G Mind Control",
        "COVID-19 Lab Leak",
        "Pizzagate",
        "New World Order",
        "Birds Aren't Real",
    ],
    "brainrot": [
        "Rizz",
        "Based",
        "Sigma Male",
        "Ohio",
        "Skibidi",
        "Gyatt",
        "NPC",
        "Mid",
        "Slay",
        "Yassified",
        "No Cap",
        "Sus",
        "Drip",
        "Goblin Mode",
        "Touch Grass",
        "Ratio",
        "OK Boomer",
        "Cheugy",
        "FYP",
        "Devious Lick",
    ],
    "history_and_eras": [
        "Civil War",
        "Revolutionary War",
        "Roaring Twenties",
        "World War III",
        "World War",
        "World War I",
        "World War II",
        "Vietnam War",
        "American Independence",
        "Civil Rights Movement",
    ],
    "memes": [
        "Chief Keef wants to blow this state up",
        "Chif Keef wants to destroy this state",
        "Chief Keef does not like this state",
        "This state is hated by Chief Keef",
    ],
    "roasts": [
        "Would not return a shopping cart",
        "Lacks the capacity for critical thought",
        "Pulls on a 'push' door",
        "Would pet a wild raccoon",
        "Would make a good podcast and should",
        "Thinks they should start a podcast but shouldn't",
        "Would fight an alligator",
        "Nick Saban",
    ],
}

"""
Interesting ones:
Fast food chains
Conspiracy Theories (JFK Assassination, Illuminati, Area 51, Montana just being consistently up there)
History (Civil War, Revolutionary War, WWI and WWII, Vietnam war)
Memes
Do Unemployed (Utah)
"""

# Pick a group. Feel free to change it here to whatever you want.
SAMPLE_STATE_QUERIES = ALL_CATEGORIES["roasts"]
